### ISSUE TITLE
dev_mini ei tule ette

### ISSUE THREAD

**Issue by kerdokullamae** [kerdokullamae/test_koik_issued#1275]
**Reported by sven syld on 27 Jan 2015 14:34 UTC**
Fatal error: Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/dev_mini/dev/htdocs/app/cache/dev_mini/appDev_miniUrlMatcher.php:2476 Stack trace: #0 /home/dev_mini/dev/htdocs/app/cache/dev_mini/classes.php(1204): appDev_miniUrlMatcher->match('/') #1 /home/dev_mini/dev/htdocs/app/cache/dev_mini/classes.php(1866): Symfony\Component\Routing\Router->match('/') #2 [function](internal): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /home/dev_mini/dev/htdocs/app/cache/dev_mini/classes.php(1661): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /home/dev_mini/dev/htdocs/app/cache/dev_mini/classes.php(1594): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #5 /home/dev_mini/dev/htdocs/app/cache/dev_mini/classes.php(1758): Symfony\Component\EventDispatcher\EventDispa in /home/dev_mini/dev/htdocs/app/cache/dev_mini/classes.php on line 1877

**Comment by kerdokullamae** [comment]
**Modified by mehis.muldma on 27 Jan 2015 15:08 UTC**

**Comment by kerdokullamae** [comment]
**Comment by mehis.muldma on 27 Jan 2015 16:46 UTC**
[2757] - Deploy oli ka veel katki, parandasin deploy ära ning muutsin konfi faile.

**Comment by kerdokullamae** [comment]
**Modified by sven.syld on 28 Jan 2015 14:33 UTC**
