### ISSUE TITLE
Importeri ja mälukasutus

### ISSUE THREAD

**Issue by kerdokullamae** [kerdokullamae/test_koik_issued#800]
**Reported by sven syld on 8 Oct 2013 09:59 UTC**
'''Object'''
 Importer

'''Description'''
 Devis reedel (04.01) käima pandud import kooles ära act/reconditioning/materials koha peal. Kuna veateadet logisse ei teki, siis parim eeldus on, et mälu sai jälle otsa. Vt import-20131004171023.log
 Mäluprobleem ei ole ilmselt ka ainult selles impordi reeglis, vaid pikemaajalisem, sest sealt alates käivitades kõik töötab.

'''Todo'''
 Parandada mälukasutust.

**Comment by kerdokullamae** [comment]
**Modified by sven.syld on 8 Oct 2013 10:03 UTC**

**Comment by kerdokullamae** [comment]
**Comment by sven.syld on 8 Oct 2013 10:05 UTC**
Lisasin 2 faili kus on tehtud (lisandunud) mälukasutuse jälgimine jne. Ehk saab snitti võtta.

**Comment by kerdokullamae** [comment]
**Comment by jaak.tamre on 9 Oct 2013 10:07 UTC**
[1891] Aktide importeri optimeerimine ja testimine.

clear() ei tohi kutsuda enne clearAllReferences(true), sest clear() kutsub ise clearAllReferences() ja siis enam ei saa deep cleari teha.

**Comment by kerdokullamae** [comment]
**Modified by sven.syld on 9 Oct 2013 13:06 UTC**

**Comment by kerdokullamae** [comment]
**Comment by jaak.tamre on 9 Oct 2013 14:26 UTC**
[1892][1894] Importerite optimeerimised ja parandusi. Estica importer testitud, nimistud tulid õigesti.

Devis RGIA.573: alamüksusi 444, nimistuid 444 (sh kattuvate nimedega)
Jaagis: RGIA.573: alamüksusi 438, nimistuid 21 (näiteks nimistu 7 all on 14 säilikut)

**Comment by kerdokullamae** [comment]
**Comment by jaak.tamre on 10 Oct 2013 06:54 UTC**
Pärast devis estica uuesti importi:
RGIA.573: alamüksusi 444, nimistuid 21

**Comment by kerdokullamae** [comment]
**Comment by sven.syld on 11 Oct 2013 07:06 UTC**
Devis fis/description_unit_person katkes (import-20131010170710.log):

  [in /home/dev/dev/htdocs/src/Brainart/XClassifierBundle/Model/om/BaseXClassifierValue.php line 679: Unable to execute INSERT statement [INSERT INTO "public"."x_classifier_value" ("id", "classifier_id", "value_id") VALU
  DETAIL:  Key (id)=(435) already exists.](PropelException])
    #0 /home/dev/dev/htdocs/src/Brainart/XClassifierBundle/Model/om/BaseXClassifierValue.php(514): Brainart\XClassifierBundle\Model\om\BaseXClassifierValue->doInsert(Object(DebugPDO))
    #1 /home/dev/dev/htdocs/src/Brainart/XClassifierBundle/Model/om/BaseXClassifierValue.php(462): Brainart\XClassifierBundle\Model\om\BaseXClassifierValue->doSave(Object(DebugPDO))
    #2 /home/dev/dev/htdocs/src/Dira/ImporterBundle/Classes/FisImporter.php(268): Brainart\XClassifierBundle\Model\om\BaseXClassifierValue->save()
    #3 [function](internal): Dira\ImporterBundle\Classes\FisImporter::importFisDescriptionUnitPerson(Array)
    #4 /home/dev/dev/htdocs/src/Dira/ImporterBundle/Classes/ImportJobCsv.php(210): call_user_func('Dira\ImporterBu...', Array)
    #5 /home/dev/dev/htdocs/src/Dira/ImporterBundle/Classes/ImportJob.php(50): Dira\ImporterBundle\Classes\ImportJobCsv->doImport()
    #6 /home/dev/dev/htdocs/src/Dira/ImporterBundle/Importer/Importer.php(228): Dira\ImporterBundle\Classes\ImportJob->import()
    #7 /home/dev/dev/htdocs/src/Dira/ImporterBundle/Importer/Importer.php(153): Dira\ImporterBundle\Importer\Importer->executeJobs(Array)
    #8 /home/dev/dev/htdocs/src/Dira/ImporterBundle/Importer/Importer.php(92): Dira\ImporterBundle\Importer\Importer->doImport(Array)
    #9 /home/dev/dev/htdocs/src/Dira/ImporterBundle/Command/ImportCommand.php(148): Dira\ImporterBundle\Importer\Importer->import(Array, true)
    #10 /home/dev/dev/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(238): Dira\ImporterBundle\Command\ImportCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Co
    #11 /home/dev/dev/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(199): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Ou
    #12 /home/dev/dev/htdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(78): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\
    #13 /home/dev/dev/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(105): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component
    #14 /home/dev/dev/htdocs/app/console(22): Symfony\Component\Console\Application->run()
    #15 {main}

**Comment by kerdokullamae** [comment]
**Comment by jaak.tamre on 11 Oct 2013 10:40 UTC**
[1904] Klassifikaatori importides oli autoincrement value vale, tehtud max value peale, mitte arv. Parandatud importerites max+1 settimise asemel max.

FIS importer ei töötanud normaalselt KÜ impordiks, korda tehtud. Täiendusi ka isikutele.

Probleem FISi csv-s, et osadel kirjetel on ylem_id sama, mis tema enda id. Seetõttu ei saa neid importida, kuna tema paigutamine hierarhiasse on võimatu. Peab olema seotud fondiga.

**Comment by kerdokullamae** [comment]
**Comment by jaak.tamre on 11 Oct 2013 12:12 UTC**
[1907] PURI genereerimine eemaldatud impordil.

**Comment by kerdokullamae** [comment]
**Comment by jaak.tamre on 11 Oct 2013 12:35 UTC**
[1908] PURI genereerimine eemaldatud veel ühest kohast. Mälukasutuse parandus FIS importeris.

**Comment by kerdokullamae** [comment]
**Modified by sven.syld on 12 Oct 2013 12:19 UTC**

**Comment by kerdokullamae** [comment]
**Comment by sven.syld on 12 Oct 2013 12:19 UTC**
[1910] parandus Postgres setval() kasutamises

**Comment by kerdokullamae** [comment]
**Modified by sven.syld on 14 Oct 2013 07:49 UTC**
